
version: '3.9'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: quickmatch
      POSTGRES_PASSWORD: quickmatch
      POSTGRES_DB: quickmatch
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
